server:
  port: 8082 # 端口

spring:
  application:
    name: product-service

  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 192.168.195.1:8848
        weight: 1
        namespace: public

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


logging:
  level:
    io.seata: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

  #Seata 配置项，对应 SeataProperties 类
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: my_product_tx_group # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      my_test_tx_group: default
    # 分组和 Seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091